'use client';

import React, { useState, useTransition } from 'react';
import Image from 'next/image';
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';
import { ScrollArea } from '@/components/ui/scroll-area';
import { placeholderImages } from '@/lib/placeholder-images';
import { getSummary } from '@/app/actions';
import { Loader2, ArrowRight } from 'lucide-react';
import type { Publication } from './publications-section';
import { useToast } from '@/hooks/use-toast';

interface PublicationCardProps {
  publication: Publication;
}

const PublicationCard: React.FC<PublicationCardProps> = ({ publication }) => {
  const [isOpen, setIsOpen] = useState(false);
  const [summary, setSummary] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();
  const { toast } = useToast();

  const paperImage = placeholderImages.find(p => p.id === publication.imageId);

  const handleSummarize = () => {
    setIsOpen(true);
    if (!summary && !error) {
      startTransition(async () => {
        const result = await getSummary(publication.paperText);
        if (result.summary) {
          setSummary(result.summary);
        } else {
          setError(result.error);
          toast({
            variant: "destructive",
            title: "Summarization Failed",
            description: result.error,
          });
        }
      });
    }
  };

  return (
    <>
      <Card className="flex flex-col overflow-hidden transition-shadow duration-300 hover:shadow-xl group">
        {paperImage && (
          <div className="overflow-hidden">
            <div className="aspect-[16/10] relative">
              <Image
                src={paperImage.imageUrl}
                alt={publication.title}
                fill
                className="object-cover transition-transform duration-500 group-hover:scale-105"
                data-ai-hint={paperImage.imageHint}
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              />
            </div>
          </div>
        )}
        <CardHeader className="p-6">
          <p className="text-sm font-medium text-primary">{publication.journal}</p>
          <CardTitle className="font-headline text-xl leading-snug">{publication.title}</CardTitle>
        </CardHeader>
        <CardContent className="flex-grow p-6 pt-0">
          <p className="text-sm text-muted-foreground">{publication.authors}</p>
        </CardContent>
        <CardFooter className="p-6 pt-0 flex-col items-start gap-4">
           <Button onClick={handleSummarize} variant="outline" className="w-full" disabled={isPending}>
            {isPending ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />Summarizing...</> : 'Get AI Summary'}
          </Button>
           <Button asChild variant="link" className="p-0 h-auto">
            <a href="#">
              Read Paper <ArrowRight className="ml-1 h-4 w-4" />
            </a>
          </Button>
        </CardFooter>
      </Card>

      <Dialog open={isOpen} onOpenChange={setIsOpen}>
        <DialogContent className="sm:max-w-2xl">
          <DialogHeader>
            <DialogTitle>AI-Powered Summary</DialogTitle>
            <DialogDescription>
              A concise summary of "{publication.title}" generated by AI.
            </DialogDescription>
          </DialogHeader>
          <ScrollArea className="max-h-[60vh] pr-4">
            {isPending ? (
              <div className="flex flex-col items-center justify-center h-48 gap-4">
                <Loader2 className="h-8 w-8 animate-spin text-primary" />
                <p className="text-muted-foreground">Generating summary...</p>
              </div>
            ) : error ? (
              <div className="text-destructive-foreground bg-destructive p-4 rounded-md">
                <h4 className="font-bold">Error</h4>
                <p>{error}</p>
              </div>
            ) : (
              <div className="space-y-4 text-sm text-foreground/90 leading-relaxed">
                {summary.split('\n').map((paragraph, index) => (
                  <p key={index}>{paragraph}</p>
                ))}
              </div>
            )}
          </ScrollArea>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsOpen(false)}>
              Close
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
};

export default PublicationCard;
